//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiamondBank.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DiamondBankEntities : DbContext
    {
        public DiamondBankEntities()
            : base("name=DiamondBankEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TBLHesap> TBLHesap { get; set; }
        public virtual DbSet<TBLMusteri> TBLMusteri { get; set; }
        public virtual DbSet<TBLIletisimBilgileri> TBLIletisimBilgileri { get; set; }
        public virtual DbSet<TBLRaporlama> TBLRaporlama { get; set; }
    }
}
