//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiamondBank.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLHesap
    {
        public int HesapID { get; set; }
        public int MusteriID { get; set; }
        public System.DateTime HesapAcilisTarihi { get; set; }
        public bool Aktiflik { get; set; }
        public decimal MevduatMiktari { get; set; }
    
        public virtual TBLMusteri TBLMusteri { get; set; }
    }
}
