//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiamondBank.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLMusteri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLMusteri()
        {
            this.TBLHesap = new HashSet<TBLHesap>();
            this.TBLIletisimBilgileri = new HashSet<TBLIletisimBilgileri>();
        }
    
        public int MusteriID { get; set; }
        public string TCNO { get; set; }
        public string UyelikTipi { get; set; }
        public string MusteriAdi { get; set; }
        public string MusteriSoyadi { get; set; }
        public string Cinsiyet { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public decimal VerilebilecekKrediMiktari { get; set; }
        public string Sifre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLHesap> TBLHesap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLIletisimBilgileri> TBLIletisimBilgileri { get; set; }
    }
}
