//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiamondBank.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLRaporlama
    {
        public int MusteriID { get; set; }
        public string IslemAciklamasi { get; set; }
        public System.DateTime IslemTarihi { get; set; }
    }
}
